# Generated by Django 6.0.1 on 2026-02-01 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="usr",
            new_name="user",
        ),
    ]
