# Generated by Django 6.0.1 on 2026-03-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="input",
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="message",
            name="output",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="message",
            name="user_message",
            field=models.TextField(max_length=500),
        ),
    ]
